name: Generate gif

on:
  push:
    branches: [main]

jobs:
  generate-gif:
    name: install project dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Generate gif
        run: | 
          uv run python3 .github/scripts/record_example_simulation.py
