name: Generate gif

on:
  push:
    branches: [main]

jobs:
  generate-gif:
    name: install project dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Generate gif
        run: | 
          uv run python3 .github/scripts/record_example_simulation.py

      - name: Commit generated gif
        run: |
          git config --global user.name 'Gifbot'
          git config --global user.email 'Gifbot@users.noreply.github.com'
          git commit -am "Automatically generate gif"
          git push
